version: '3.9'


services:
  pgdb:
    image: "postgres:14.3"
    container_name: roomer_db
    env_file:
      - .env/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - roomer_db_data:/var/lib/postgresql/data

  roomer_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roomer_api
    env_file:
      - .env/.env.dev
    volumes:
      - ./:/opt/app
    depends_on:
      - pgdb
    entrypoint: ""
    command: /home/roomer/docker-entrypoint.sh
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: "roomer-rabbitmq"
    ports:
      - "5673:5672"
      - "15672:15672"
    env_file:
      - .env/.env.rabbitmq
    volumes:
      - roomer-data-rabbitmq:/var/lib/rabbitmq/mnesia/

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "roomer-celery-worker"
    env_file:
      - .env/.env.dev
    volumes:
      - .:/opt/app
    depends_on:
      - pgdb
      - roomer_api
      - rabbitmq
    entrypoint: ""
    command: celery -A roomer worker --loglevel=INFO --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info


volumes:
  roomer_db_data:
  roomer-data-rabbitmq:
