# Generated by Django 4.0 on 2023-01-12 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Deleted', verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username Field', max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
