# Generated by Django 4.0 on 2023-01-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('users', '0002_alter_user_deleted_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.ForeignKey(blank=True, help_text='Phone Code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.phonecode'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=256, null=True, verbose_name='phone_number'),
        ),
    ]
