# Generated by Django 4.0 on 2023-01-18 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', django.db.models.expressions.F('start_time'))), name='start_end_time_check'),
        ),
    ]
