# Generated by Django 4.0 on 2023-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='start_time'),
        ),
    ]
