# Generated by Django 4.0 on 2023-01-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0003_user_phone_code_user_phone_number'),
        ('booking', '0004_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(help_text='Room', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='users.user'),
        ),
    ]
