# Generated by Django 4.0 on 2023-01-17 13:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_options_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='start_end_time_check',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', django.db.models.expressions.F('start_time'))), name='start_end_time_check'),
        ),
    ]
